cmd_parser: Split cmd_parser to multiple functions
It started to generate the following error message even though we
still have some space in the "Program space".

    error: (1347) can't find 0x878 words (0x878 withtotal) for psect
    "text19" in class "CODE" (largest unused contiguous range 0x800)

Refactor "chkreg" command out to its own function to make cmd_parser()
smaller.

https://microchipdeveloper.com/faq:45

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>